version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: kusls-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: KUSLS_db
      MYSQL_USER: KUSLS_user
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - kusls-net

  be:
    image: taehee/kusls:latest
    container_name: kusls-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/KUSLS_db
      DB_USERNAME: KUSLS_user
      DB_PASSWORD: ${DB_USER_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      TZ: Asia/Seoul
    volumes:
      - ./config:/config
    networks:
      - kusls-net

volumes:
  db-data:

networks:
  kusls-net:
