server:
  port: 8080

jwt:
  secret: Z/OINAaLvB4OAbtlNvzZCnlElJdYtRnHnAE0mjXKCK8=
  expiration: 3600000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/KUSLS_db
    username: root
    password: 0129
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
