name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/KUSLS-key.pem
          chmod 600 ~/.ssh/KUSLS-key.pem

      - name: Add EC2 to known hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/KUSLS-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/KUSLS-Back
            git fetch origin master
            git reset --hard origin/master
            chmod +x gradlew
            ./gradlew build
            sudo systemctl start docker
            sudo /usr/local/bin/docker-compose up --build -d
          EOF
      
