name: KUSLS CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: 빌드 및 배포
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: DockerHub 로그인
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker 이미지 빌드 및 푸시
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kusls:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/kusls:latest

      - name: deploy.sh 업로드
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: deploy.sh
          target: ~/KUSLS-Back/

      - name: docker-compose.yml 업로드
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: docker-compose.yml
          target: ~/KUSLS-Back/

      - name: .env 업로드
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: .env
          target: ~/KUSLS-Back/

      - name: 배포 스크립트 실행
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/KUSLS-Back
            chmod +x deploy.sh
            ./deploy.sh

